= java-mavenmixin-jettywar
:_imagesdir: ./
:toc:


This module, for use within link:http://isis.apache.org[Apache Isis] applications, provides a link:https://github.com/odavid/maven-plugins[maven mixin] that can be used to package up a webapp using the run the `package` goal of the link:http://maven.apache.org/plugins/maven-war-plugin/index.html[Maven war plugin], and to run that webapp using the `run` goal of the link:https://www.eclipse.org/jetty/documentation/9.3.x/jetty-maven-plugin.html[Jetty plugin].
This reduces the size of the maven `pom.xml` file for that consuming module; it simply needs to reference _this_ module using the `mixin-maven-plugin`.

The appropriate configuration is included in a `<profile>` which is automatically included in all builds.
This profile can be disabled using a Maven property.



== How to Configure

To configure:

* copy and paste the following into either the `pom.xml` of the consuming module or (better still) the `pom.xml` of the top-level parent of the consuming module: +
+
[source,xml]
----
<properties>
    ...
    <mavenmixin-jettywar.version>0.0.2</mavenmixin-jettywar.version>
    
    <maven-war-plugin.version>2.4</maven-war-plugin.version>
    <jetty-maven-plugin.version>9.3.5.v20151012</jetty-maven-plugin.version>
    ...
</properties>
----
+
and: +
+
[source,xml]
----
<build>
    <pluginManagement>
        <plugins>
            ...
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>${maven-war-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>${jetty-maven-plugin.version}</version>
            </plugin>
            ...
        </plugins>
    </pluginManagement>
</build>
----

* update the following property/ies in the `pom.xml` of the consuming webapp module (with `<packaging>war</packaging>`): +
+
[source,xml]
----
<properties>
    ...
    <maven-war-plugin.warName>${project.parent.artifactId}</maven-war-plugin.warName>          <!--1-->
    ...
</properties>
----
<1> the name of the war file to generate.

* add the following to the `pom.xml` of the consuming module: +
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.github.odavid.maven.plugins</groupId>
            <artifactId>mixin-maven-plugin</artifactId>
            <version>0.1-alpha-39</version>
            <extensions>true</extensions>
            <configuration>
                <mixins>
                    <mixin>
                        <groupId>com.danhaywood.mavenmixin</groupId>
                        <artifactId>jettywar</artifactId>
                        <version>${mavenmixin-jettywar.version}</version>
                    </mixin>
                </mixins>
            </configuration>
        </plugin>
    </plugins>
</build>
----



The packaging sets up a manifest that references two properties, `maven.version` and `agent.name`.
These are not defined under normal circumstances (and if they remain unset then the manifest will simply not report this information).
But if you wish, you can define the `maven.version` property, using the `build-helper-maven-plugin`:

[source,xml]
----
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <version>1.8</version>
    <executions>
        <execution>
            <phase>validate</phase>
            <goals>
                <goal>maven-version</goal>
            </goals>
        </execution>
    </executions>
</plugin>
----

As for `agent.name`, this can be set up by the continuous integration server.

To disable the (profile contributed by this) mixin, pass the following system property to `mvn`:

[source,bash]
----
mvn -Dskip.mavenmixin-jettywar
----


== How to use

To package the WAR file:

[source,bash]
----
mvn package
----

To run the webapp using Jetty:

[source,bash]
----
mvn -pl webapp jetty:run
----

(where `webapp` is the module that uses this mixin).



== Known issues

None currently



== Change Log

* `0.0.2` - updates README for properties and plugin management, shortens property names and profile id
* `0.0.1` - first release; released using `maven-war-plugin:2.4` and `jetty-maven-plugin:9.3.5.v20151012`




== Legal Stuff

=== License

[source]
----
Copyright 2016~date Dan Haywood

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----



=== Dependencies

This mixin module relies on the link:https://github.com/odavid/maven-plugins[com.github.odavid.maven.plugins:mixin-maven-plugin], released under Apache License v2.0.



== Maven deploy notes

The module is deployed using Sonatype's OSS support (see
http://central.sonatype.org/pages/apache-maven.html[user guide] and http://www.danhaywood.com/2013/07/11/deploying-artifacts-to-maven-central-repo/[this blog post]).

The `release.sh` script automates the release process.
It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.2 \
              0.0.3-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where

* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the ``pgp-maven-plugin``'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master
git push origin 0.0.2
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue before trying again.
Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the `autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).
You may want to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
